name: Build & Release APK

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: ./app/build/outputs/apk/release/*.apk => Spent.apk