name: Build & Release APK

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore & Build Signed APK
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
#          echo $SIGNING_KEY_BASE64 | base64 --decode > release.jks
          echo $SIGNING_KEY_BASE64 | base64 --decode > app/release.jks
          ./gradlew assembleRelease

      - name: Rename and move APK
        run: mv ./app/build/outputs/apk/release/app-release.apk ./Spent.apk

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: Spent.apk